### ISSUE TITLE
I like how you used divs to organize your code

### ISSUE THREAD

**Issue by jzhu01** [sebastianschipper/dasmoto#1]
Seen here: 
https://github.com/sebastianschipper/dasmoto/blob/b35b66c5237291706f35762c42df7cedf177d12b/index.html#L15-L20

This provides structure to your code and makes it easier to read. Nice! :)

**Comment by sebastianschipper** [comment]
Thank you! At first I wasn`t sure to use divs in that way, because I thought that could be unnecessary code. But as I looked on it after inserting the divs, I was pleased of what I was looking on. Even rendered in DevTools the code looks more organized in that way.
