### ISSUE TITLE
Suggestion - no need to specify font-weight: bold on h1 and h2

### ISSUE THREAD

**Issue by jzhu01** [sebastianschipper/dasmoto#2]
Seen here: https://github.com/sebastianschipper/dasmoto/blob/b35b66c5237291706f35762c42df7cedf177d12b/resources/css/style.css#L4

Since the headings are bolded by default, there's no need to specify this here.

**Comment by sebastianschipper** [comment]
OK, thank you! I did not know that headings are bold by default. Now I know ;-)
