### ISSUE TITLE
Suggestion - set the font-family once using a body selector

### ISSUE THREAD

**Issue by jzhu01** [sebastianschipper/dasmoto#3]
Seen here: 
https://github.com/sebastianschipper/dasmoto/blob/b35b66c5237291706f35762c42df7cedf177d12b/resources/css/style.css#L3

Since this line is repeated throughout your code, it makes more sense to set it once to avoid repetition.

**Comment by sebastianschipper** [comment]
Yes, I was thinking about that, but did not implement it in that way. Thank you for this suggestion, next time, I will reduce such kinds of repetition.
